name: C++ Clang-Format and Build

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cpp@v1
        with:
          cpp-version: '20'

      - name: Build
        run: |
          g++ -std=c++20 -o my_program main.cpp

      - name: Clang-Format Check
        run: |
          clang-format -i main.cpp
          git diff --exit-code || exit 1

