name: C/C++ Linter

on:
  push:
    branches:
      - main  # Set your desired branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all commit history for accurate linting

      - name: Setup C/C++ environment
        run: |
          sudo apt-get -y update
          sudo apt-get -y install clang-tidy clang-format
          # Install clang-tidy and clang-format

      - name: Run C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2.6.1
        with:
          thread-comments: false  # Optional, disable thread comments
          step-summary: false     # Optional, disable step summary
          file-annotations: true  # Optional, enable file annotations
          style: llvm             # Optional, set the code style (e.g., llvm, file)
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'  # Optional, specify file extensions
          tidy-checks: 'boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*'  # Optional, specify clang-tidy checks
          repo-root: .            # Optional, specify the repo root path
          version: 12             # Optional, set the desired clang tools version
          verbosity: 10           # Optional, set log verbosity
          lines-changed-only: true    # Optional, only analyze changes in the event's diff
          files-changed-only: true    # Optional, analyze only source files in the repo
          ignore: '.github'       # Optional, specify paths to ignore
          database: ''            # Optional, specify the directory containing compile_commands.json
          extra-args: ''          # Optional, add extra arguments to clang-tidy

